name: Docker Image Publish

on:
  push:
    branches:
    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v2
      with:
        # Container registry username
        username: ${{ secrets.SAMPLEAPP_ACR_USERNAME }}
        # Container registry password
        password: ${{ secrets.SAMPLEAPP_ACR_PASSWORD }}
        # Container registry server url
        login-server: github.com
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:         
        docker build . --file WebApp.Dockerfile --tag api.github.com/seandentener:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag api.github.com/seandentener:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER api.github.com/seandentener:latest;
        docker push api.github.com/seandentener:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        # docker push github.com/seandentener:latest;  
      
